<template>
  <div id="mainIndex">
    1asdasds
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
    <p>asdas</p>
  </div>
</template>

<script>
  export default {
    name: 'mainIndex'
  }
</script>

<style>

</style>
